-- Supabase/PostgreSQL schema for land-ocr-180.
-- Structured data moves from Google Sheets; Google My Drive remains the file store.

create extension if not exists citext with schema extensions;

create table public.users (
  email extensions.citext primary key,
  roles text[] not null check (
    cardinality(roles) > 0 and roles <@ array[
      'SYSTEM_ADMIN','WARD_ADMIN','INTAKE_OFFICER','REVIEW_OFFICER',
      'POPULATION_MATCH_OFFICER','REPORT_VIEWER','AUDITOR'
    ]::text[]
  ),
  active boolean not null default true,
  display_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.audit_logs (
  audit_id uuid primary key default gen_random_uuid(),
  occurred_at timestamptz not null default now(),
  actor_email text not null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  request_id text not null,
  metadata jsonb not null default '{}'::jsonb
);
create index audit_logs_entity_idx on public.audit_logs (entity_type, entity_id, occurred_at desc);

create table public.request_log (
  idempotency_key text primary key,
  request_id text not null,
  kind text not null,
  mutation_hash text not null,
  response_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index request_log_expiry_idx on public.request_log (expires_at);

create table public.public_submissions (
  submission_id text primary key,
  receipt_code extensions.citext not null unique,
  status text not null default 'DRAFT' check (status in (
    'DRAFT','SUBMITTED','UNDER_REVIEW','NEEDS_SUPPLEMENT','RESUBMITTED','ACCEPTING',
    'ACCEPTED','NO_ACTION_REQUIRED','REJECTED','EXPIRED'
  )),
  -- Legacy Sheets may contain an empty/invalid phone; new API writes validate it before insert.
  phone text not null check (phone = '' or phone ~ '^0[0-9]{9}$'),
  version integer not null default 1 check (version > 0),
  access_code_hash text not null,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  locked_until timestamptz,
  consent_version text not null,
  consented_at timestamptz not null default now(),
  retention_until timestamptz,
  official_case_id text,
  drive_folder_id text not null,
  accept_step text,
  claimed_by text,
  claimed_at timestamptz,
  draft_json jsonb,
  access_version integer not null default 1 check (access_version > 0),
  file_summary_json jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  legacy_row_index bigint generated by default as identity unique
);
create index public_submissions_status_updated_idx
  on public.public_submissions (status, updated_at desc);
create index public_submissions_claimed_idx
  on public.public_submissions (claimed_by, updated_at desc) where claimed_by is not null;
create index public_submissions_draft_gin_idx
  on public.public_submissions using gin (draft_json jsonb_path_ops);

create table public.public_files (
  file_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  owner_id text not null default '',
  document_type text not null check (document_type in ('CITIZEN_ID_FRONT','CITIZEN_ID_BACK','CERTIFICATE')),
  variant text not null default 'ORIGINAL' check (variant in ('ORIGINAL','PREVIEW')),
  drive_file_id text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  checksum_sha256 text not null,
  status text not null default 'UPLOADED' check (status in ('UPLOADED','REPLACED','DELETED')),
  file_name text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index public_files_submission_idx on public.public_files (submission_id, status, document_type);
create unique index public_files_active_identity_side_idx
  on public.public_files (submission_id, owner_id, document_type)
  where status = 'UPLOADED' and document_type in ('CITIZEN_ID_FRONT','CITIZEN_ID_BACK');

create table public.public_status_events (
  event_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  event_type text not null,
  label text not null,
  actor_email text not null,
  actor_display_name text not null,
  message text not null default '',
  occurred_at timestamptz not null,
  request_id text not null
);
create index public_status_events_submission_idx
  on public.public_status_events (submission_id, occurred_at);

create table public.public_supplement_requests (
  supplement_request_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  status text not null check (status in ('OPEN','RESOLVED')),
  reason_code text not null,
  message text not null,
  requested_by_email text not null,
  requested_by_display_name text not null,
  created_at timestamptz not null,
  resolved_at timestamptz
);
create unique index public_one_open_supplement_idx
  on public.public_supplement_requests (submission_id) where status = 'OPEN';

create table public.public_supplement_items (
  item_id text primary key,
  supplement_request_id text not null references public.public_supplement_requests(supplement_request_id),
  submission_id text not null references public.public_submissions(submission_id),
  item_type text not null,
  target_entity_type text not null,
  target_entity_id text not null default '',
  field_path text not null default '',
  document_type text,
  reason_code text not null,
  instruction text not null,
  status text not null check (status in ('OPEN','RESOLVED')),
  created_at timestamptz not null,
  resolved_at timestamptz
);
create index public_supplement_items_request_idx
  on public.public_supplement_items (supplement_request_id, status);

create table public.public_certificates (
  certificate_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  issue_number text not null,
  issue_date text not null default '',
  registry_number text not null default '',
  created_at timestamptz not null default now()
);

create table public.public_owners (
  owner_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  owner_type text not null,
  full_name text not null,
  identity_number text not null default '',
  role_on_certificate text not null default '',
  date_of_birth text not null default '',
  gender text not null default '',
  residence_address text not null default '',
  identity_source text not null default '',
  qr_payload_hash text not null default '',
  qr_decoder_version text not null default '',
  qr_parser_version text not null default '',
  identity_status text not null default '',
  identity_confirmed_at text not null default '',
  has_distinct_current_user boolean not null default false,
  current_user_name text not null default '',
  current_user_citizen_id text not null default '',
  current_user_address text not null default '',
  change_reason text not null default '',
  created_at timestamptz not null default now()
);
create index public_owners_submission_idx on public.public_owners (submission_id);

create table public.public_parcels (
  parcel_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  parcel_id_code text not null default '',
  map_sheet_number text not null default '',
  parcel_number text not null default '',
  address_on_certificate text not null default '',
  address_two_level text not null default '',
  area text not null default '',
  old_ward text not null default '',
  created_at timestamptz not null default now()
);

create table public.public_land_uses (
  land_use_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  parcel_id text not null references public.public_parcels(parcel_id),
  purpose_code text not null,
  purpose_free_text text not null default '',
  origin_code text not null default '',
  form_code text not null default '',
  term_code text not null default '',
  area text not null default '',
  created_at timestamptz not null default now()
);

create table public.public_assets (
  asset_id text primary key,
  submission_id text not null references public.public_submissions(submission_id),
  asset_type text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

create table public.existing_certificates (
  row_version bigint generated always as identity primary key,
  existing_record_id text not null,
  issue_number text not null default '',
  issue_number_normalized text not null default '',
  issue_date text not null default '',
  registry_number text not null default '',
  status text not null,
  source_name text not null default '',
  source_row text not null default '',
  imported_at timestamptz not null default now()
);
create index existing_certificates_latest_idx
  on public.existing_certificates (existing_record_id, row_version desc);

create table public.existing_certificate_owners (
  row_version bigint generated always as identity primary key,
  existing_owner_link_id text not null,
  existing_record_id text not null,
  citizen_id_hmac text not null,
  source_name text not null default '',
  imported_at timestamptz not null default now()
);
create index existing_certificate_owners_hmac_idx
  on public.existing_certificate_owners (citizen_id_hmac, row_version desc);

create table public.public_existing_record_links (
  link_id uuid primary key default gen_random_uuid(),
  submission_id text not null references public.public_submissions(submission_id),
  owner_id text not null,
  existing_record_id text not null,
  outcome text not null,
  status text not null default 'ACTIVE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (submission_id, owner_id, existing_record_id, status)
);

create table public.existing_import_runs (
  run_row_id bigint generated always as identity primary key,
  import_run_id text not null,
  source_sha256 text not null,
  status text not null,
  source_name text not null default '',
  stats_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table public.public_lookup_index (
  lookup_id bigint generated always as identity primary key,
  kind text not null check (kind in ('EXISTING','PENDING')),
  citizen_id_hmac text not null,
  existing_record_id text,
  submission_id text references public.public_submissions(submission_id),
  created_at timestamptz not null default now(),
  check (
    (kind = 'EXISTING' and existing_record_id is not null and submission_id is null)
    or (kind = 'PENDING' and submission_id is not null and existing_record_id is null)
  )
);
create index public_lookup_index_hmac_idx on public.public_lookup_index (citizen_id_hmac, kind);
create unique index public_lookup_existing_unique
  on public.public_lookup_index (citizen_id_hmac, existing_record_id) where kind = 'EXISTING';
create unique index public_lookup_pending_unique
  on public.public_lookup_index (citizen_id_hmac, submission_id) where kind = 'PENDING';

create table public.export_jobs (
  export_job_id text primary key,
  export_type text not null,
  status text not null check (status in ('COMPLETED','ARCHIVE_FAILED')),
  drive_file_id text not null default '',
  file_name text not null,
  row_count integer not null,
  submission_count integer not null,
  warning_count integer not null,
  checksum_sha256 text not null,
  actor_email text not null,
  scope_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  completed_at timestamptz not null
);

create table public.cases (
  case_id text primary key,
  neighborhood_code text not null,
  neighborhood_name text not null,
  status text not null,
  intake_officer_email text,
  assigned_reviewer_email text,
  received_at timestamptz,
  updated_at timestamptz not null default now(),
  notes text not null default '',
  version integer not null default 1,
  drive_folder_id text not null
);

create table public.certificates (
  certificate_id text primary key,
  case_id text not null references public.cases(case_id),
  issue_number text not null,
  issue_date text not null default '',
  registry_number text not null default '',
  land_user_name text not null default '',
  notes text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.owners (
  owner_id text primary key,
  case_id text not null references public.cases(case_id),
  full_name text not null,
  citizen_id text not null default '',
  date_of_birth text not null default '',
  gender text not null default '',
  address text not null default '',
  source text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.files (
  file_id text primary key,
  case_id text not null references public.cases(case_id),
  owner_id text,
  document_type text not null,
  variant text not null,
  drive_file_id text not null,
  mime_type text not null,
  size_bytes bigint not null,
  checksum_sha256 text not null,
  status text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.identity_qr_scans (
  scan_id text primary key,
  case_id text not null references public.cases(case_id),
  owner_id text,
  citizen_id text not null default '',
  full_name text not null default '',
  date_of_birth text not null default '',
  gender text not null default '',
  address text not null default '',
  payload_hash text not null,
  decoder_version text not null,
  parser_version text not null,
  status text not null,
  confirmed_by text,
  confirmed_at timestamptz
);

create table public.reference_data (
  category text not null,
  code text not null,
  label text not null,
  active boolean not null default true,
  sort_order integer not null default 0,
  primary key (category, code)
);

create table public.id_reservations (
  reservation_id bigint generated always as identity primary key,
  year integer not null,
  created_at timestamptz not null default now(),
  request_id text not null unique,
  actor_email text not null
);

create table public.search_index (
  index_id text primary key,
  case_id text not null references public.cases(case_id),
  field text not null,
  value_hash text not null,
  updated_at timestamptz not null default now()
);
create index search_index_lookup_idx on public.search_index (field, value_hash);

create table public.parcels (
  parcel_id text primary key,
  case_id text not null references public.cases(case_id),
  data_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.assets (
  asset_id text primary key,
  case_id text not null references public.cases(case_id),
  data_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.ocr_fields (
  ocr_field_id text primary key,
  case_id text,
  checksum_sha256 text,
  model_version text,
  payload_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The app never exposes the Data API directly. RLS remains enabled with no anon/authenticated
-- policies; the server connects through the private PostgreSQL connection string.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users','audit_logs','request_log','public_submissions','public_files','public_status_events',
    'public_supplement_requests','public_supplement_items','public_certificates','public_owners',
    'public_parcels','public_land_uses','public_assets','existing_certificates',
    'existing_certificate_owners','public_existing_record_links','existing_import_runs',
    'public_lookup_index','export_jobs','cases','certificates','owners','files','identity_qr_scans',
    'reference_data','id_reservations','search_index','parcels','assets','ocr_fields'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon, authenticated', table_name);
  end loop;
end
$$;

revoke all on all sequences in schema public from anon, authenticated;